### ISSUE TITLE
Unslider-一个超小的jQuery轮播插件

### ISSUE THREAD

**Issue by zhouqihang** [zhouqihang/zhouqihang.com#2]
Unslider轮播插件的压缩版本还不到3K，它不仅跨浏览器、支持键盘导航、自动调整高度，而且还支持响应式布局！Uslider的使用很简单，只需要四步：
1.引入jQuery和Unslider
```html
<script src="//code.jquery.com/jquery-latest.min.js"></script>
<script src="//unslider.com/unslider.js"></script>
```
2.构建一个HTML无序列表
```html
<div class="banner">
    <ul>
        <li>This is a slide.</li>
        <li>This is another slide.</li>
        <li>This is a final slide.</li>
    <ul>
</div>
```
3.设置css样式
```css
.banner { position: relative; overflow: auto; }
.banner li { list-style: none; }
.banner ul li { float: left; }
```
4.调用
```js
$(function() {
    $('.banner').unslider();
});
```
Unslider官网: [http://unslider.com/](http://unslider.com/)
GitHub地址: [https://github.com/idiot/unslider](https://github.com/idiot/unslider)
